In [14]:
import tensorflow as tf
import numpy as np

In [18]:
def map_tuple(x, y):
    y = tf.one_hot(y, depth=3)
    return x, y

def map_dict(ds):
    x = ds['x']
    y = ds['y']
    y = tf.one_hot(y, depth=3)
    return {'x': x, 'y': y}

x = np.array([[1, 2], [3, 4], [5, 6]])
y = np.array([0, 1, 2])

d_dict = {'x': x, 'y': y}
ds_dict = tf.data.Dataset.from_tensor_slices( d_dict )
ds_dict = ds_dict.map(lambda ds: map_dict(ds))
for data in ds_dict:
    print(data['x'], data['y'])
print("")

d_tuple = (x, y)
ds_tuple = tf.data.Dataset.from_tensor_slices( d_tuple )
# If the dataset is tuple, map function needs two input arguments
ds_tuple = ds_tuple.map(lambda a, b: map_tuple(a, b))
for data in ds_tuple:
    print(data[0], data[1])

tf.Tensor([1 2], shape=(2,), dtype=int32) tf.Tensor([1. 0. 0.], shape=(3,), dtype=float32)
tf.Tensor([3 4], shape=(2,), dtype=int32) tf.Tensor([0. 1. 0.], shape=(3,), dtype=float32)
tf.Tensor([5 6], shape=(2,), dtype=int32) tf.Tensor([0. 0. 1.], shape=(3,), dtype=float32)

tf.Tensor([1 2], shape=(2,), dtype=int32) tf.Tensor([1. 0. 0.], shape=(3,), dtype=float32)
tf.Tensor([3 4], shape=(2,), dtype=int32) tf.Tensor([0. 1. 0.], shape=(3,), dtype=float32)
tf.Tensor([5 6], shape=(2,), dtype=int32) tf.Tensor([0. 0. 1.], shape=(3,), dtype=float32)
